
#cloud-config
hostname: ${hostname}
users:
  - name: debian
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBKKMgnN8zJCxrlpBlTc14/SaBZ/shFsEsoFqZttbx2R

chpasswd:
  list: |
    debian:debian
  expire: False

growpart:
  mode: auto
  devices: ["/"]
  ignore_growroot_disabled: false

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent

runcmd:
  - [ systemctl, start, qemu-guest-agent ]
